### ISSUE TITLE
h2 request fails with REFUSED_STREAM error

### ISSUE THREAD

**Issue by klingerf** [BuoyantIO/linkerd#760] opened 2016-10-19 19:17 UTC
I'm trying to configure linkerd to talk to http2.golang.org, which serves HTTP/2 requests with TLS.

I can curl the site (using prior knowledge and disabling certificate validation):

```
$ curl -s --http2 --http2-prior-knowledge -k https://http2.golang.org:443/reqinfo
Method: GET
Protocol: HTTP/2.0
Host: http2.golang.org
...
```

But when I run linkerd with a similar config:

```
routers:
- protocol: h2
  experimental: true
  baseDtab: |
    /h2 => /$/inet/http2.golang.org/443;
  servers:
  - port: 4142
  client:
    tls:
      kind: io.l5d.noValidation
```

Then the curl command hangs:

```
$ curl -s --http2 --http2-prior-knowledge -v http://localhost:4142/reqinfo
*   Trying ::1...
* TCP_NODELAY set
* connect to ::1 port 4142 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 4142 (#0)
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7f882200f000)
> GET /reqinfo HTTP/1.1
> Host: localhost:4142
> User-Agent: curl/7.50.3
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
```

In the linkerd logs, I see:

```
E 1019 19:12:14.938 THREAD78: demuxer
com.twitter.finagle.ChannelClosedException: ChannelException at remote address: http2.golang.org/130.211.116.44:443. Remote Info: Not Available
```

For context, here's the whole log with netty logging enabled:

```
INFO 1019 12:14:43.238 finagle/netty4-3: 
----------------OUTBOUND--------------------
[id: 0xf1580aa6, L:/127.0.0.1:4142 - R:/127.0.0.1:54205] SETTINGS: ack=false, settings={}
------------------------------------
INFO 1019 12:14:43.238 finagle/netty4-3: 
----------------INBOUND--------------------
[id: 0xf1580aa6, L:/127.0.0.1:4142 - R:/127.0.0.1:54205] SETTINGS: ack=false, settings={}
------------------------------------
INFO 1019 12:14:43.238 finagle/netty4-3: 
----------------OUTBOUND--------------------
[id: 0xf1580aa6, L:/127.0.0.1:4142 - R:/127.0.0.1:54205] SETTINGS: ack=true
------------------------------------
INFO 1019 12:14:43.239 finagle/netty4-3: 
----------------INBOUND--------------------
[id: 0xf1580aa6, L:/127.0.0.1:4142 - R:/127.0.0.1:54205] HEADERS: streamId=1, headers=DefaultHttp2Headers[:method: GET, :path: /reqinfo, :scheme: http, :authority: localhost:4142, user-agent: curl/7.50.3, accept: */*], padding=0, endStream=true
------------------------------------
1019 19:14:43.249 fa963b7cb402f926.fa963b7cb402f926<:fa963b7cb402f926] Message(namer.success)
INFO 1019 12:14:43.259 finagle/netty4-3: 
----------------INBOUND--------------------
[id: 0xf1580aa6, L:/127.0.0.1:4142 - R:/127.0.0.1:54205] SETTINGS: ack=true
------------------------------------
INFO 1019 12:14:43.332 finagle/netty4-4: 
----------------OUTBOUND--------------------
[id: 0x0fbea0d1, L:/192.168.1.7:54206 - R:http2.golang.org/130.211.116.44:443] SETTINGS: ack=false, settings={}
------------------------------------
DEBUG 1019 12:14:43.426 finagle/netty4-4: Accepting a server certificate: CN=http2.golang.org, O=Google Inc, L=Mountain View, ST=California, C=US
INFO 1019 12:14:43.491 finagle/netty4-4: 
----------------OUTBOUND--------------------
[id: 0x0fbea0d1, L:/192.168.1.7:54206 - R:http2.golang.org/130.211.116.44:443] HEADERS: streamId=3, headers=DefaultHttp2Headers[:method: GET, :path: /reqinfo, :scheme: http, :authority: localhost:4142, user-agent: curl/7.50.3, accept: */*, l5d-dst-logical: /h2/localhost:4142, via: h2 linkerd, l5d-dst-concrete: /$/inet/http2.golang.org/443, l5d-dst-residual: /localhost:4142], streamDependency=0, weight=16, exclusive=false, padding=0, endStream=true
------------------------------------
DEBUG 1019 12:14:43.493 finagle/netty4-4: [id: 0x0fbea0d1, L:/192.168.1.7:54206 - R:http2.golang.org/130.211.116.44:443] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
INFO 1019 12:14:43.554 finagle/netty4-4: 
----------------OUTBOUND--------------------
[id: 0x0fbea0d1, L:/192.168.1.7:54206 - R:http2.golang.org/130.211.116.44:443] GO_AWAY: lastStreamId=0, errorCode=1, length=77, bytes=4669727374207265636569766564206672616d6520776173206e6f742053455454494e47532e204865782064756d7020666f7220666972737420352062797465...
------------------------------------
DEBUG 1019 12:14:43.555 finagle/netty4-4: [id: 0x0fbea0d1, L:/192.168.1.7:54206 - R:http2.golang.org/130.211.116.44:443] Sending GOAWAY failed: lastStreamId '0', errorCode '1', debugData 'First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f'. Forcing shutdown of the connection.
javax.net.ssl.SSLException: SSLEngine closed already
    at io.netty.handler.ssl.SslHandler.wrap(...)(Unknown Source)
E 1019 19:14:43.561 THREAD86: demuxer
com.twitter.finagle.ChannelClosedException: ChannelException at remote address: http2.golang.org/130.211.116.44:443. Remote Info: Not Available
```

**Comment by wmorgan** [comment] 2016-12-13 18:47
This should be fixed in 0.8.4. Please reopen if not.

**Comment by klingerf** [comment] 2016-12-14 02:01
Going to reopen this issue, since I still can't use linkerd to proxy requests to http2.golang.org, but this might just be user error, so feel free to re-close if so.

As stated in the initial description, I can send an insecure HTTP/2 request directly to http2.golang.org:

```
$ curl -s --http2 --http2-prior-knowledge -k https://http2.golang.org:443/reqinfo
Method: GET
Protocol: HTTP/2.0
Host: http2.golang.org
...
```

But I can't seem to configure linkerd to successfully make the same request.  Here's my linkerd config:

```
routers:
- protocol: h2
  experimental: true
  baseDtab: |
    /h2 => /$/inet/http2.golang.org/443;
  servers:
  - port: 4142
  client:
    tls:
      kind: io.l5d.noValidation
```

But when I send a request to linkerd, I get:

```
$ curl -s --http2 --http2-prior-knowledge -v http://localhost:4142/reqinfo
*   Trying ::1...
* TCP_NODELAY set
* connect to ::1 port 4142 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 4142 (#0)
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7ff04b00b000)
> GET /reqinfo HTTP/1.1
> Host: localhost:4142
> User-Agent: curl/7.50.3
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
* HTTP/2 stream 1 was not closed cleanly: REFUSED_STREAM (err 7)
* Curl_http_done: called premature == 1
* Closing connection 0
```

And there are a bunch of exceptions in linkerd's logs:

```
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:571)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:512)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:426)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:398)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.twitter.finagle.util.ProxyThreadFactory$$anonfun$newProxiedRunnable$1$$anon$1.run(ProxyThreadFactory.scala:19)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLHandshakeException: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE
	at io.netty.handler.ssl.OpenSslEngine.shutdownWithError(OpenSslEngine.java:620)
	at io.netty.handler.ssl.OpenSslEngine.sslReadErrorResult(OpenSslEngine.java:823)
	at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:777)
	at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:855)
	at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:898)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1094)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:966)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:900)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	... 18 more

W 1214 02:00:06.194 THREAD76: Unhandled exception in connection with http2.golang.org/130.211.116.44:443, shutting down connection
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:571)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:512)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:426)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:398)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.twitter.finagle.util.ProxyThreadFactory$$anonfun$newProxiedRunnable$1$$anon$1.run(ProxyThreadFactory.scala:19)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLHandshakeException: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE
	at io.netty.handler.ssl.OpenSslEngine.shutdownWithError(OpenSslEngine.java:620)
	at io.netty.handler.ssl.OpenSslEngine.sslReadErrorResult(OpenSslEngine.java:823)
	at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:777)
	at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:855)
	at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:898)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1094)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:966)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:900)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	... 18 more

WARN 1213 18:00:06.196 finagle/netty4-2: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:571)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:512)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:426)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:398)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.twitter.finagle.util.ProxyThreadFactory$$anonfun$newProxiedRunnable$1$$anon$1.run(ProxyThreadFactory.scala:19)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLHandshakeException: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE
	at io.netty.handler.ssl.OpenSslEngine.shutdownWithError(OpenSslEngine.java:620)
	at io.netty.handler.ssl.OpenSslEngine.sslReadErrorResult(OpenSslEngine.java:823)
	at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:777)
	at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:855)
	at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:898)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1094)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:966)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:900)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	... 18 more
W 1214 02:00:06.303 THREAD78: ChannelStatsHandler caught an exception
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:571)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:512)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:426)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:398)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.twitter.finagle.util.ProxyThreadFactory$$anonfun$newProxiedRunnable$1$$anon$1.run(ProxyThreadFactory.scala:19)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLHandshakeException: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE
	at io.netty.handler.ssl.OpenSslEngine.shutdownWithError(OpenSslEngine.java:620)
	at io.netty.handler.ssl.OpenSslEngine.sslReadErrorResult(OpenSslEngine.java:823)
	at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:777)
	at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:855)
	at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:898)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1094)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:966)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:900)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	... 18 more
```

**Comment by klingerf** [comment] 2016-12-14 02:03
I should have noted in my last comment: linkerd no longer hangs. It returns right away, but with the REFUSED_STREAM error.

**Comment by olix0r** [comment] 2016-12-14 15:18
this was fixed in 0.8.4

**Comment by wmorgan** [comment] 2017-01-05 20:50
Current status: not fixed yet, but on our radar.

**Comment by olix0r** [comment] 2017-01-11 00:18
@klingerf were you running this in Docker? I want to ensure that we're both in the same config, since I can't reproduce the exceptions that you saw. I do still see _some_ sort of error, though:
```
INFO 0110 23:53:05.263 finagle/netty4-2: 
----------------OUTBOUND--------------------
[id: 0x31a8f10c, L:/192.168.1.187:64330 - R:http2.golang.org/130.211.116.44:443] SETTINGS: ack=false, settings={}
------------------------------------
DEBUG 0110 23:53:05.325 finagle/netty4-2: Accepting a server certificate: CN=http2.golang.org
D 0110 23:53:05.423 THREAD1153757 TraceId:72714965c2ffaa63: [C L:/192.168.1.187:64330 R:http2.golang.org/130.211.116.44:443 S:3] initialized stream
INFO 0110 23:53:05.433 finagle/netty4-2: 
----------------OUTBOUND--------------------
[id: 0x31a8f10c, L:/192.168.1.187:64330 - R:http2.golang.org/130.211.116.44:443] HEADERS: streamId=3, headers=DefaultHttp2Headers[:method: GET, :path: /, :scheme: http, :authority: localhost:4142, user-agent: curl/7.52.1, accept: */*, l5d-dst-logical: /h2/localhost:4142, via: h2 linkerd, l5d-dst-concrete: /$/inet/http2.golang.org/443], streamDependency=0, weight=16, exclusive=false, padding=0, endStream=true
------------------------------------
DEBUG 0110 23:53:05.460 finagle/netty4-2: [id: 0x31a8f10c, L:/192.168.1.187:64330 - R:http2.golang.org/130.211.116.44:443] HANDSHAKEN: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
INFO 0110 23:53:05.525 finagle/netty4-2: 
----------------OUTBOUND--------------------
[id: 0x31a8f10c, L:/192.168.1.187:64330 - R:http2.golang.org/130.211.116.44:443] GO_AWAY: lastStreamId=0, errorCode=1, length=77, bytes=4669727374207265636569766564206672616d6520776173206e6f742053455454494e47532e204865782064756d7020666f7220666972737420352062797465...
------------------------------------
DEBUG 0110 23:53:05.531 finagle/netty4-2: [id: 0x31a8f10c, L:/192.168.1.187:64330 - R:http2.golang.org/130.211.116.44:443] Sending GOAWAY failed: lastStreamId '0', errorCode '1', debugData 'First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f'. Forcing shutdown of the connection.
javax.net.ssl.SSLException: SSLEngine closed already
	at io.netty.handler.ssl.SslHandler.wrap(...)(Unknown Source)
E 0110 23:53:05.560 THREAD1153757: [C L:/192.168.1.187:64330 R:http2.golang.org/130.211.116.44:443] dispatcher failed
com.twitter.finagle.ChannelClosedException: ChannelException at remote address: http2.golang.org/130.211.116.44:443. Remote Info: Not Available
```

Especially: _First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f._

It looks like the client immediately tears down the connection after (it thinks) the TLS handshake is completed.  However, the mystery deepens: `485454502f` is the hex representation of `HTTP/`, as if we receive a plain-old HTTP response.

Perhaps we're not correctly negotiating HTTP/2 via ALPN?

**Comment by klingerf** [comment] 2017-01-11 00:34
@olix0r Just checked, and I'm now seeing the same error as you in the netty debug log output.

**Comment by olix0r** [comment] 2017-01-11 01:24
I put together a simple [debug server](https://gist.github.com/olix0r/74d4c968b3c7034127a6462ac1c7e51b) serving over TLS.

What we see is that a request from curl to debug server looks like:
```
GET / HTTP/2.0
User-Agent: curl/7.52.1
Accept: */*
```

Requests routed through linkerd hit the debug server with:
```
PRI * HTTP/2.0
```

AFAIU, we shouldn't be sending the magic preamble after TLS, so I think this is the linkerd bug.

**Comment by olix0r** [comment] 2017-01-11 01:40
aside: Wireshark can't decrypt streams with diffie helman key exchange is performed, so it's not all that easy to debug the communication from outside the processes...  Perhaps we should change linkerd to support configurable ciphers (at some point).

**Comment by olix0r** [comment] 2017-01-11 05:34
Nope, that won't matter. HTTP/2 requires ciphers that wireshark can't decode:
```
Error: http2: TLSConfig.CipherSuites is missing HTTP/2-required TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256. Try --help for help.
exit status 255
```

So, looks like we're going to have to debug this from inside the app.

I think I understand what's going on now, though. Shoutout to [nghttpd](https://github.com/nghttp2/nghttp2) for being a super helpful server to test against:

```
:; nghttpd -v 4443 debug_priv.pem debug_pub.pem 
IPv4: listen 0.0.0.0:4443
IPv6: listen :::4443
[ALPN] client offers:
 * h2
 * http/1.1
SSL/TLS handshake completed
The negotiated protocol: h2
[id=1] [  5.126] send SETTINGS frame <length=6, flags=0x00, stream_id=0>
          (niv=1)
          [SETTINGS_MAX_CONCURRENT_STREAMS(0x03):100]
[id=1] [  5.146] recv SETTINGS frame <length=12, flags=0x00, stream_id=0>
          (niv=2)
          [SETTINGS_MAX_CONCURRENT_STREAMS(0x03):100]
          [SETTINGS_INITIAL_WINDOW_SIZE(0x04):1073741824]
[id=1] [  5.146] recv WINDOW_UPDATE frame <length=4, flags=0x00, stream_id=0>
          (window_size_increment=1073676289)
[id=1] [  5.146] recv (stream_id=1) :method: GET
[id=1] [  5.146] recv (stream_id=1) :path: /
[id=1] [  5.146] recv (stream_id=1) :scheme: https
[id=1] [  5.146] recv (stream_id=1) :authority: localhost:4443
[id=1] [  5.146] recv (stream_id=1) user-agent: curl/7.52.1
[id=1] [  5.146] recv (stream_id=1) accept: */*
[id=1] [  5.146] recv HEADERS frame <length=30, flags=0x05, stream_id=1>
          ; END_STREAM | END_HEADERS
          (padlen=0)
          ; Open new stream
[id=1] [  5.146] recv SETTINGS frame <length=0, flags=0x01, stream_id=0>
          ; ACK
          (niv=0)
[id=1] [  5.146] send SETTINGS frame <length=0, flags=0x01, stream_id=0>
          ; ACK
          (niv=0)
[id=1] [  5.146] send HEADERS frame <length=69, flags=0x04, stream_id=1>
          ; END_HEADERS
          (padlen=0)
          ; First response header
          :status: 404
          server: nghttpd nghttp2/1.17.0
          date: Wed, 11 Jan 2017 05:31:06 GMT
          content-type: text/html; charset=UTF-8
          content-length: 147
[id=1] [  5.146] send DATA frame <length=147, flags=0x01, stream_id=1>
          ; END_STREAM
[id=1] [  5.146] stream_id=1 closed
[id=1] [  5.147] closed
SSL/TLS handshake completed
Client did not advertise HTTP/2 protocol. (nghttp2 expects h2)
[id=2] [ 27.900] closed
```

It seems likely that linkerd's protocol negotiation isn't configured properly. I'll look into that.

**Comment by olix0r** [comment] 2017-01-11 07:25
It turns out that Finagle doesn't actually support client-side ALPN today.

But fear not! I've done the netty version of monkeypatching to get client ALPN working.  Review forthcoming; and then we can figure out how to upstream a proper fix.

(Aside: I guess that this means that the grpc-go server doesn't actually care about client alpn, which is odd).

It turns out there are several tls configuration options not exposed as params on the finagle stack.  @vkostyukov @mosesn @ryanoneill We'd definitely like the ability to configure TLS protocols, ciphers, etc via the stack. Any guidance on the best approach?  Additional TlsConfig types?

**Closed** 2017-01-14 00:25 UTC
Labels: reviewable
