### ISSUE TITLE
Kubernetes namespace watches sometimes hang indefinitely

### ISSUE THREAD

**Issue by olix0r** [BuoyantIO/linkerd#83] opened 2016-02-09 20:27 UTC
We've observed a bug in the kubernetes namer where name resolution (and requests) hang indefinitely when initializing a watch on a second namespace.

For example, in a test cluster, we launch an application into the `prod` namespace and do continuous deployment to a `pre-prod` namespace that may be accessed with an override.

The configuration contains:
```yaml
namers:
- kind: io.l5d.experimental.k8s
  prefix: /ns
  tlsWithoutValidation: true
  authTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
```
and a base dtab like:
```
  /iface => /io.l5d.k8s/prod;
  /method => /$/io.buoyant.http.anyMethodPfx/iface ;
  /http/1.1 => /method ;
  ...
```

Requests are routed to the pre-prod namespace with an override like:
```
/iface => /io.l5d.k8s/pre-prod | /$/fail;
```

Initially, we observe requests through prod operating as expected, resolving through the k8s namer:
```
D 0126 23:45:28.991 THREAD29: k8s initializing service0
...
D 0126 23:45:29.327 THREAD30: k8s ns prod initial state: service0
...
D 0126 23:45:42.955 THREAD30: k8s lookup: /pre-prod/http/service0 /pre-prod/http/service0
D 0126 23:45:42.956 THREAD30: k8s initializing pre-prod
```

And we see no further k8s logging after this.  Furthermore, because the namer never satisfies this  lookup, the request never succeeds and remains pending until the client disconnects

Something appears to be wrong in the kubernetes namer that prevents this second watch from succeeding.

**Comment by siggy** [comment] 2016-02-26 05:58
#### linkerd-0.2.1-SNAPSHOT confirmed working

testing with `linkerd-helium:sig3` (`linkerd-0.2.1-SNAPSHOT`), in namespace `sig`, works with `prod` and  `pre-prod`:

```
$ curl -H 'L5d-sample: 0' -H 'Dtab-local: /ns/sig=>/ns/prod;' http://23.251.154.236
$ curl -H 'L5d-sample: 0' -H 'Dtab-local: /ns/sig=>/ns/pre-prod;' http://23.251.154.236
```
```
$ kubectl --namespace=sig logs sproxy-ix56f -c l5d -f
...
D 0226 05:53:17.541 THREAD31: k8s lookup: /prod/router/web /prod/router/web
D 0226 05:53:17.546 THREAD31: k8s initializing prod
D 0226 05:53:17.546 THREAD31: k8s initializing2 prod
D 0226 05:53:17.546 THREAD31: k8s endpoints Promise@1296927950(state=Transforming(List(<function1>, <function1>),Promise@280773399(state=Transforming(List(<function1>),Promise@1529645848(state=Done(Return(<function1>)))))))
D 0226 05:53:17.577 THREAD31 org.jboss.netty.handler.ssl.SslHandler: [id: 0x967a7988, /10.196.5.26:39833 => kubernetes.default.cluster.local/10.199.240.1:443] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
D 0226 05:53:17.588 THREAD31: k8s ns prod initial state: auth, users, sessions, web, projects, sproxy, events, accounts
D 0226 05:53:17.588 THREAD31: k8s ns prod service web found
D 0226 05:53:17.588 THREAD31: k8s ns prod service web port router found + /
I 0226 05:53:17.594 THREAD31: Using web as the TLS common name for /ns/prod/router/web
I 0226 05:53:17.595 THREAD31: Using web as the TLS common name for /ns/prod/router/web
D 0226 05:53:17.622 THREAD28 org.jboss.netty.handler.ssl.SslHandler: [id: 0x5e2f4847, /10.196.5.26:56384 => /10.196.1.26:4140] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
...
D 0226 05:53:33.712 THREAD31: k8s lookup: /pre-prod/router/web /pre-prod/router/web
D 0226 05:53:33.737 THREAD31: k8s initializing pre-prod
D 0226 05:53:33.737 THREAD31: k8s initializing2 pre-prod
D 0226 05:53:33.737 THREAD31: k8s endpoints Promise@812482979(state=Transforming(List(<function1>, <function1>),Promise@291983516(state=Transforming(List(<function1>),Promise@1672547676(state=Done(Return(<function1>)))))))
D 0226 05:53:33.763 THREAD30 org.jboss.netty.handler.ssl.SslHandler: [id: 0x43ec29ea, /10.196.5.26:39864 => kubernetes.default.cluster.local/10.199.240.1:443] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
D 0226 05:53:33.771 THREAD30: k8s ns pre-prod initial state: auth, users, sessions, web, projects, events, accounts
D 0226 05:53:33.771 THREAD30: k8s ns pre-prod service web found
D 0226 05:53:33.771 THREAD30: k8s ns pre-prod service web port router found + /
I 0226 05:53:33.777 THREAD30: Using web as the TLS common name for /ns/pre-prod/router/web
I 0226 05:53:33.777 THREAD30: Using web as the TLS common name for /ns/pre-prod/router/web
D 0226 05:53:33.814 THREAD31 org.jboss.netty.handler.ssl.SslHandler: [id: 0x299458a2, /10.196.5.26:54610 => /10.196.3.44:4140] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
```

#### linkerd-0.1.1-SNAPSHOT confirmed failing

testing with `linkerd-helium:sig` (`linkerd-0.1.1-SNAPSHOT`), in namespace `sig`, hanging on `pre-prod`:

```
$ curl -H 'L5d-sample: 0' -H 'Dtab-local: /ns/sig=>/ns/pre-prod;' http://23.251.154.236
```
```
$ kubectl --namespace=sig logs sproxy-gmheu -c l5d -f
...
D 0226 03:11:52.455 THREAD29: k8s lookup: /pre-prod/router/web /pre-prod/router/web
D 0226 03:11:52.455 THREAD29: k8s initializing pre-prod
E 0226 03:12:36.760 THREAD29: Exception propagated to the root monitor!
com.twitter.finagle.CancelledRequestException: request cancelled
    at com.twitter.finagle.NoStacktrace(Unknown Source)

E 0226 03:12:36.761 THREAD29: service failure
com.twitter.finagle.CancelledRequestException: request cancelled
    at com.twitter.finagle.NoStacktrace(Unknown Source)

E 0226 03:12:36.761 THREAD29: Exception propagated to the root monitor!
com.twitter.finagle.CancelledRequestException: request cancelled
    at com.twitter.finagle.NoStacktrace(Unknown Source)

D 0226 03:12:36.762 THREAD29: ChannelStatsHandler caught an exception
java.nio.channels.ClosedChannelException
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.cleanUpWriteBuffer(AbstractNioWorker.java:433)
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.writeFromUserCode(AbstractNioWorker.java:128)
```

**Comment by siggy** [comment] 2016-02-26 06:01
This issue no longer manifests following https://github.com/BuoyantIO/linkerd/pull/137, though an underlying bug may still exist.

**Comment by siggy** [comment] 2016-02-29 20:56
Reported issue to finagle:
https://github.com/twitter/finagle/issues/471

**Comment by jimmidyson** [comment] 2016-04-10 08:54
I'm still seeing this issue with 0.3.0. Any tips on the best way to debug this?

**Comment by olix0r** [comment] 2016-04-11 16:03
@jimmidyson if you run linkerd with the `-log.level=DEBUG` and `-com.twitter.finagle.tracing.debugTrace=true` flags, your logs should be a bit more verbose.

If you can grab a snapshot of the stats in on :9990/admin/metrics.json when the process is in this state, that would be helpful, too.

Also, we'll be better able to help if you share your linkerd config (especially your dtab) -- this is a common source of confusion.

Finally, would you mind explaining how this state arises?  What version of kubernetes you're running, etc?

Thanks!

**Comment by jimmidyson** [comment] 2016-04-11 21:39
Thanks for the tips. Very possible this is just a misunderstanding about the dtab - have found it slightly confusing so have tried to make it as simple as possible:

```yaml
admin:                                                                          
  port: 9990                                                                    
                                                                                
namers:                                                                         
- kind: io.l5d.experimental.k8s                                                 
  host: localhost                                                               
  port: 8443                                                                    
  tls: true                                                                     
  tlsWithoutValidation: true                                                                                                                                                                  
  authTokenFile: /home/jdyson/tmp/token                                         
                                                                                
routers:                                                                        
- protocol: http                                                                
  baseDtab: |                                                                   
    /http/1.1/GET => /io.l5d.k8s/zipkin/http;                                   
  label: int                                                                    
  servers:                                                                      
  - port: 4140                                                                  
    ip: 0.0.0.0
```

Running `curl -H 'Host: zipkin-web-console' localhost:4140`. The service `zipkin-web-console` does exist in the namespace `zipkin` with the named port `http`. It's almost like it's not querying at all.

Here's the (hopefully) relevant part of the logs:

```
D 0411 21:25:53.631 THREAD19: k8s lookup: /zipkin/http/zipkin-web-console /zipkin/http/zipkin-web-console
D 0411 21:25:53.649 THREAD19: k8s initializing zipkin
0411 21:25:53.652 36e4dfa7003f8c8b.36e4dfa7003f8c8b<:36e4dfa7003f8c8b] BinaryAnnotation(namer.dtab.base,/http/1.1/GET=>/io.l5d.k8s/zipkin/http)
0411 21:25:53.652 36e4dfa7003f8c8b.36e4dfa7003f8c8b<:36e4dfa7003f8c8b] BinaryAnnotation(namer.dtab.local,)
0411 21:25:53.652 36e4dfa7003f8c8b.36e4dfa7003f8c8b<:36e4dfa7003f8c8b] BinaryAnnotation(namer.path,/http/1.1/GET/zipkin-web-console)
```

Here's the output from :9990/admin/metrics.json: https://gist.github.com/jimmidyson/c05a0e7959b52a5dde50bb2837ea3782

If it does turn out to be config problems, hanging isn't great of course.

**Comment by wmorgan** [comment] 2016-04-11 23:01
Sounds like a proper bug. Reopening and assigning to Oliver.

**Comment by wmorgan** [comment] 2016-04-11 23:11
After some internal discussion, Alex will take a look at this.

**Comment by adleong** [comment] 2016-04-12 00:22
Hi @jimmidyson, thanks for the info.  This behavior can happen if linkerd in unable to connect to the k8s API.  We've got a couple of issues tracking making this situation easier to debug including adding better logging (#272) and adding a timeout for name resolution (#273).

In your particular case it looks like you've got the k8s namer configured to talk to localhost.  Do you have the k8s master running on localhost?  Or are you running through a proxy?  In the case of a proxy, it's likely that TLS won't work and you'll need to turn that off in your config.

Can you check if you're able to hit the k8s API manually on localhost:8443 over https?

**Comment by jimmidyson** [comment] 2016-04-12 10:16
@adleong I'm running this just for dev, local builds from master & running locally, & I have Kubernetes (well OpenShift actually) running locally too, accessible at https://localhost:8443. TLS works but of course with cert validation disabled (as I tried to do with the config). So yeah `curl https://localhost:8443` works fine. I've actually also tried setting up a little proxy to capture requests & see that no requests reach the proxy on localhost. The timeout for name resolution is really important - it would help with quick diagnosis of issues like this but still in production consumers would want to have a quick response if lookups fail, just like DNS failures.

Trying to debug through the namer but being a bit of a n00b to scala it makes it a bit difficult. One thing I have noticed is that the filters don't seem to work properly. I added a quick System.out (yeah, dirty but effective :-b) to both the SetHostFilter & AuthFilter & the SetHostFilter doesn't get called for some reason:

```
Authfilter Request("GET /api/v1/namespaces/zipkin/endpoints", from 0.0.0.0/0.0.0.0:0)
```

When I swap round the order of `filtered` calls in `namer/k8s/src/main/scala/io/l5d/k8s.scala` it does actually call the SetHostFilter too:

```
SetHostFilter Request("GET /api/v1/namespaces/zipkin/endpoints", from 0.0.0.0/0.0.0.0:0)
Authfilter Request("GET /api/v1/namespaces/zipkin/endpoints", from 0.0.0.0/0.0.0.0:0)
```

So it could be something odd in the filter stack going on?

**Comment by jimmidyson** [comment] 2016-04-12 11:05
So testing the calls via curl:

    curl -k -H "Authorization: Bearer $(cat ~/tmp/token)" https://localhost:8443/api/v1/namespaces/zipkin/endpoints

works fine so I know both the API server URL & token file are correct.

**Comment by adleong** [comment] 2016-04-12 16:41
thanks for digging into this, @jimmidyson!

Agreed that timeouts are important, we're adding them soon.  As for the behavior you discovered with the filters: that's very strange.  The behavior you found suggests that something is going wrong in the AuthFilter, but if you take a look at the contents of that filter, it's pretty simple.

We're going to try setting up kuberenetes locally to see if we can reproduce the issue.  In the meantime, I encourage you to keep digging and let us know if you find anything.

**Comment by adleong** [comment] 2016-04-12 16:51
Could you also post the full linkerd log when running with `-log.level=DEBUG` and `-com.twitter.finagle.tracing.debugTrace=true` and exercising the issue?

**Comment by jimmidyson** [comment] 2016-04-12 18:53
I've turned off auth & removed the auth filter... & querying works... I cannot explain that at all as you said AuthFilter is ridiculously simple.

**Comment by jimmidyson** [comment] 2016-04-12 18:56
It's this line in AuthFilter that's hanging:

    req.headerMap("Authorization") = s"Bearer $token"

**Comment by jimmidyson** [comment] 2016-04-12 19:46
Here's the [full log](https://gist.github.com/jimmidyson/953ca1dab448d7f983d043dea36aa279).

**Comment by adleong** [comment] 2016-04-12 21:41
I've found a potential explanation.  Does your auth token file end with a newline?  Attempting to set a header value with a new line causes an exception.  Unfortunately, that exception is getting swallowed and not logged today, which makes this kind of thing very hard to debug.  We'll definitely fix that in #272.  In the meantime, try stripping out any newlines from your token file and see if that helps.

**Comment by jimmidyson** [comment] 2016-04-12 22:33
You've got it - new line removed & works great. Well it's a newline char without a new line (just learnt about the eol option in vim). That is really annoying - sorry for the noise (but yeah something in the logs would be great).

**Comment by wmorgan** [comment] 2016-04-12 22:36
Amazing.

**Comment by adleong** [comment] 2016-04-12 22:36
Glad to hear it!  This definitely showcases the need for better error logging.  Stay tuned.

**Closed** 2016-04-12 22:37 UTC
Labels: bug, ready

**Comment by jimmidyson** [comment] 2016-04-12 22:38
Thanks for your help figuring this one out - now I can get on & play more :)
