### ISSUE TITLE
A lot of exceptions in Namerd with k8s storage

### ISSUE THREAD

**Issue by moleksyuk** [BuoyantIO/linkerd#627] opened 2016-09-06 08:41 UTC
Hi,

I have deployed `Namerd` into Kubernetes with such configs:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: namerd-sync
spec:
  selector:
    app: namerd
  ports:
  - name: sync
    port: 4100
---
apiVersion: v1
kind: Service
metadata:
  name: namerd-api
spec:
  selector:
    app: namerd
  ports:
  - name: api
    port: 4180
---
metadata:
  name: d-tab.l5d.io # the hyphen is required by the Kubernetes API. This will be converted to the CamelCase name "DTab".
apiVersion: extensions/v1beta1
kind: ThirdPartyResource
description: stores dtabs used by Buoyant's `namerd` service
versions:
  - name: v1alpha1 # Do not change this value as it hardcoded in Namerd and doesn't work with other value.
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: namerd-config
data:
  config.yml: |-
    admin:
      port: 9991
    storage:
      kind: io.l5d.k8s
      experimental: true
    namers:
      - kind: io.l5d.k8s
        experimental: true
        host: 127.0.0.1
        port: 8001
    interfaces:
      - kind: io.l5d.thriftNameInterpreter
        ip: 0.0.0.0
        port: 4100
      - kind: io.l5d.httpController
        ip: 0.0.0.0
        port: 4180
---
kind: ReplicationController
apiVersion: v1
metadata:
  name: namerd
spec:
  replicas: 1
  selector:
    app: namerd
  template:
    metadata:
      labels:
        app: namerd
    spec:
      dnsPolicy: ClusterFirst
      volumes:
        - name: namerd-config
          configMap:
            name: namerd-config
      containers:
        - name: namerd
          image: buoyantio/namerd:0.7.4
          args:
            - /io.buoyant/namerd/config/config.yml
            - -com.twitter.finagle.tracing.debugTrace=true
            - -log.level=DEBUG
          imagePullPolicy: Always
          ports:
            - name: sync
              containerPort: 4100
            - name: api
              containerPort: 4180
          volumeMounts:
            - name: "namerd-config"
              mountPath: "/io.buoyant/namerd/config"
              readOnly: true
        - name: kubectl
          image: buoyantio/kubectl:1.2.3
          args:
          - "proxy"
          - "-p"
          - "8001"
          imagePullPolicy: Always
```

When I try to get all available dtabs (which is empty after deployment) I start see a lot of errors complaining to not accesible api and some exceptions. And these errors still appear all the time wheather dtab(s) created or deleted.

Errors complain about not accessible `/apis/l5d.io/v1alpha1/namespaces/default/dtabs` but it accessible and I can get results from k8s. Looks strange.

Attaching complete log file...
[namerd-exceptions.txt](https://github.com/BuoyantIO/linkerd/files/456278/namerd-exceptions.txt)

**Comment by adleong** [comment] 2016-09-06 17:07
Hi @moleksyuk!  Just to confirm, this ticket is just about the noisy exceptions in the logs, right?  You aren't seeing any incorrect behavior?  

I think we can clean up the log exceptions with something similar to this: https://github.com/BuoyantIO/linkerd/commit/8085c4c5b6a7dc5f4a6e77b4669cca383e1b63eb

**Comment by OleksandrBerezianskyi** [comment] 2016-09-08 10:49
hey Alex, the problem we observed was that (for some reason) Namerd stopped to change the dtab in underlying k8s storage through API (while still returning 204). Maybe the real issue was buried under these exception messages. Initially we thought that these exceptions were the cause, but after the restart we could not reproduce the behaviour, so I think we should just close this ticket and reopen it if we have any reasonable steps to reproduce.

**Comment by adleong** [comment] 2016-09-09 18:13
I think we can keep this issue open to track cleaning up the noisy exceptions in the logs.  What's going on is that every time a observation on the k8s api is released, that `Closed` exception is hitting the root monitor and being logged.  Instead, we should change the `io.buoyant.k8s.Api.Closed` to be a finagle `Failure` with the `Interrupted`flag and also add a monitor to the k8s client to swallow interrupted failures.  See https://github.com/BuoyantIO/linkerd/commit/8085c4c5b6a7dc5f4a6e77b4669cca383e1b63eb where we did this for the consul client.

**Closed** 2016-09-27 23:51 UTC
Labels: hacktoberfest, help wanted
