### ISSUE TITLE
Cannot open DTab page in Admin UI

### ISSUE THREAD

**Issue by gaugau** [BuoyantIO/linkerd#827] opened 2016-11-28 04:07 UTC
Hi,

I've followed the example for creating linkerd with namerd on the repo. 
https://github.com/BuoyantIO/linkerd-examples/blob/master/k8s-daemonset/k8s
But when I open the admin page and click on 'dtab' link, it does not work.  A guy on slacks suggested that I should open an issue as it's perhaps a bug.
Here are details:

Version: 0.8.3
Kubernetes: 1.4.0 on CoreOS (via kube-aws)
Configuration files:

https://gist.github.com/gaugau/379310f88913728e53bef7b2cbdde417

Thanks

**Comment by siggy** [comment] 2016-11-28 05:39
may be a duplicate of https://github.com/BuoyantIO/linkerd/pull/821

**Comment by gaugau** [comment] 2016-11-28 07:10
@siggy Does it mean that it's a bug from linkerd? Or the configuration from examples is not correct?!

**Comment by siggy** [comment] 2016-11-28 08:43
@gaugau It's a bug in linkerd. You can verify this by hitting the `/config.json` endpoint on your linkerd admin port, or just open up your browser dev console while viewing the dtab page.

**Comment by olix0r** [comment] 2016-11-28 23:27
Does linkerd log anything?

**Closed** 2016-12-05 18:10 UTC
