### ISSUE TITLE
Marathon namer should return only addresses of tasks in RUNNING state

### ISSUE THREAD

**Issue by jacob-koren** [BuoyantIO/linkerd#941] opened 2017-01-18 09:32 UTC
Marathon namer currently returns IP:port of all tasks that exists for a specific application. 
https://github.com/BuoyantIO/linkerd/blob/master/marathon/src/main/scala/io/buoyant/marathon/v2/Api.scala
` def getAddrs(app: Path): Future[Set[Address]] = {
    **val req = http.Request(s"$apiPrefix/apps${app.show}?embed=app.tasks")**
    Trace.letClear(client(req)).flatMap(rspToAddrs(_, useHealthCheck))
  }`

This means that during a rolling upgrade of application, the namer returns bind addresses of STAGING and KILLED tasks as well as RUNNING tasks. Which makes this operation a non-zero downtime operation.

I think that only RUNNING tasks should be returned. Combined with marathon upgrade strategy*, we can reach a zero downtime upgrade without using more sophisticated processes like B/G upgrade where it's not needed.

* `"upgradeStrategy": {
    "minimumHealthCapacity": 1,
    "maximumOverCapacity": 0.5
  },`

**Comment by wmorgan** [comment] 2017-01-18 17:03
Here's what @siggy said in Slack. (See https://linkerd.io/features/service-discovery/ for some more motivation about this advisory treatment.)

Regarding our Marathon namer not honoring the `RUNNING` state, that is by design. Marathon apps are available more than just when the state is `RUNNING`, due to lag between periodic Marathon health checks. Also, if an instance becomes unavailable, linkerd will notice immediately upon a failed request, and retry a healthy instance. We expect this to give you better zero downtime behavior during upgrade than using the `RUNNING` state, because you instances will be available earlier during startup and later during shutdown.

All that said, if you still only want to hit instances marked as `RUNNING`, you can enable the `useHealthCheck` flag in your linkerd config: https://linkerd.io/config/0.8.5/linkerd/index.html#marathon-service-discovery-experimental

**Comment by jacob-koren** [comment] 2017-01-18 17:24
Thanks, Is the retry a default behavior? Because right now we do see failed requests

**Comment by siggy** [comment] 2017-01-18 18:53
Hi @jacob-koren. By default linkerd retries connection failures, but not application failures, which may be what you are hitting. The linkerd DC/OS package is configured conservatively to avoid retrying requests that may not be idempotent.

If you'd like to configure more aggressive retries, have a look at:
https://linkerd.io/config/0.8.5/linkerd/index.html#http-response-classifiers
https://linkerd.io/config/0.8.5/linkerd/index.html#retries

If you do decide to deploy a custom-configured linkerd onto DC/OS, you can follow along here:
https://linkerd.io/getting-started/dcos/#deploying-a-custom-linkerd

**Comment by jacob-koren** [comment] 2017-01-19 09:49
Hi, I tried the useHealthCheck option. It didn't solve the problem mainly because TASK_KILLING state is not considered unhealthy. After marathon send the sig TERM there were no additional health check calls.

Here's an example of one of the tasks of the application that is KILLING state during the upgrade:
`"tasks": [
   {
     "id": “someid”,
     "slaveId": “someslaveid”,
     "state": "TASK_KILLING",
     "version": "2017-01-19T09:11:38.714Z",
     "healthCheckResults": [
       {
         "alive": true,
         "consecutiveFailures": 0,
         "firstSuccess": "2017-01-19T09:11:44.272Z",
         "lastFailure": null,
         "lastSuccess": "2017-01-19T09:21:11.473Z",
         "lastFailureCause": null,
       }
     ]
   },`

I'll continue with the retry and see if it's solves the issue

**Comment by siggy** [comment] 2017-01-19 18:19
Thanks for the detailed report @jacob-koren. You're right, I think if `useHealthCheck` is enabled, linkerd should look at both `"state": "TASK_KILLING"` and `"healthCheckResults": [ { "alive": true...`.

A little more detail for my own context:
https://mesosphere.github.io/marathon/docs/health-checks.html

**Comment by wmorgan** [comment] 2017-01-20 01:16
To clarify: the desired behavior is that when `useHealthCheck` is enabled for the marathon namer, linkerd should only use endpoints where `"healthCheckResults": [ { "alive": true...` and `state` is *not* `TASK_KILLING`.

Is that right?

**Comment by siggy** [comment] 2017-01-20 01:20
Correct. To be slightly more specific, when `useHealthCheck` is enabled, we should check for `"healthCheckResults": [ { "alive": true...` and `state` is `TASK_RUNNING`

**Closed** 2017-01-20 22:28 UTC
Labels: help wanted, marathon, reviewable
